run:
  timeout: 5m
  modules-download-mode: readonly

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/mattermost/mattermost-plugin-apps
  govet:
    check-shadowing: true
    enable-all: true
    disable:
      - fieldalignment
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - bodyclose
    - errcheck
    - gocritic
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - staticcheck
    - stylecheck
    - revive
    - typecheck
    - unconvert
    - unused
    - unparam
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - bodyclose
        - scopelint # https://github.com/kyoh86/scopelint/issues/4
    - path: test/restapitest
      linters:
        - bodyclose
        - unused
        - unparam
        - staticcheck
    - path: /
      linters:
        - staticcheck
      text: "BotJoined"
    - path: /
      linters:
        - staticcheck
      text: "BotLeft"


