services:
    node_app:
        image: node:13
        ports:
            - "4000:4000"
        working_dir: /app
        environment:
            MATTERMOST_SITEURL: http://mattermost:8066
            NODE_HOST: node_app # Should be the same as the "service" name above
            PORT: 4000

        volumes:
            - ./node_app:/app
            # or
            # - ../../path/to/my/app:/app
        command: bash -c "npm i && npm start"
        # or
        # command: bash -c "(install dependencies) && (run application)"

        # You should only need the (install dependencies) step when your dependencies change.
