// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mattermost/mattermost-plugin-apps/server/config (interfaces: Service)

// Package mock_config is a generated GoMock package.
package mock_config

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	pluginapi "github.com/mattermost/mattermost-plugin-api"
	i18n "github.com/mattermost/mattermost-plugin-api/i18n"
	config "github.com/mattermost/mattermost-plugin-apps/server/config"
	telemetry "github.com/mattermost/mattermost-plugin-apps/server/telemetry"
	utils "github.com/mattermost/mattermost-plugin-apps/utils"
	configservice "github.com/mattermost/mattermost-server/v6/services/configservice"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockService) Get() config.Config {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].(config.Config)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockServiceMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockService)(nil).Get))
}

// I18N mocks base method.
func (m *MockService) I18N() *i18n.Bundle {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "I18N")
	ret0, _ := ret[0].(*i18n.Bundle)
	return ret0
}

// I18N indicates an expected call of I18N.
func (mr *MockServiceMockRecorder) I18N() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "I18N", reflect.TypeOf((*MockService)(nil).I18N))
}

// MattermostAPI mocks base method.
func (m *MockService) MattermostAPI() *pluginapi.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MattermostAPI")
	ret0, _ := ret[0].(*pluginapi.Client)
	return ret0
}

// MattermostAPI indicates an expected call of MattermostAPI.
func (mr *MockServiceMockRecorder) MattermostAPI() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MattermostAPI", reflect.TypeOf((*MockService)(nil).MattermostAPI))
}

// MattermostConfig mocks base method.
func (m *MockService) MattermostConfig() configservice.ConfigService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MattermostConfig")
	ret0, _ := ret[0].(configservice.ConfigService)
	return ret0
}

// MattermostConfig indicates an expected call of MattermostConfig.
func (mr *MockServiceMockRecorder) MattermostConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MattermostConfig", reflect.TypeOf((*MockService)(nil).MattermostConfig))
}

// Reconfigure mocks base method.
func (m *MockService) Reconfigure(arg0 config.StoredConfig, arg1 utils.Logger, arg2 ...config.Configurable) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Reconfigure", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reconfigure indicates an expected call of Reconfigure.
func (mr *MockServiceMockRecorder) Reconfigure(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reconfigure", reflect.TypeOf((*MockService)(nil).Reconfigure), varargs...)
}

// StoreConfig mocks base method.
func (m *MockService) StoreConfig(arg0 config.StoredConfig, arg1 utils.Logger) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreConfig", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreConfig indicates an expected call of StoreConfig.
func (mr *MockServiceMockRecorder) StoreConfig(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreConfig", reflect.TypeOf((*MockService)(nil).StoreConfig), arg0, arg1)
}

// Telemetry mocks base method.
func (m *MockService) Telemetry() *telemetry.Telemetry {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Telemetry")
	ret0, _ := ret[0].(*telemetry.Telemetry)
	return ret0
}

// Telemetry indicates an expected call of Telemetry.
func (mr *MockServiceMockRecorder) Telemetry() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Telemetry", reflect.TypeOf((*MockService)(nil).Telemetry))
}
