// This file is automatically generated. Do not modify it manually.

package main

import (
	"strings"

	"github.com/mattermost/mattermost-server/v5/model"
)

var manifest *model.Manifest

const manifestStr = `
{
  "id": "com.mattermost.apps",
  "name": "Apps",
  "description": "Apps Registry and API proxy.",
  "homepage_url": "https://github.com/mattermost/mattermost-plugin-apps",
  "support_url": "https://github.com/mattermost/mattermost-plugin-apps/issues",
  "release_notes_url": "https://github.com/mattermost/mattermost-plugin-apps/releases/tag/v0.5.0",
  "version": "0.5.0",
  "min_server_version": "5.26.0",
  "server": {
    "executables": {
      "darwin-amd64": "server/dist/plugin-darwin-amd64",
      "linux-amd64": "server/dist/plugin-linux-amd64",
      "windows-amd64": "server/dist/plugin-windows-amd64.exe"
    },
    "executable": ""
  },
  "settings_schema": {
    "header": "",
    "footer": "To report an issue, make a suggestion or a contribution, [check the repository](https://github.com/mattermost/mattermost-plugin-apps).",
    "settings": []
  }
}
`

func init() {
	manifest = model.ManifestFromJson(strings.NewReader(manifestStr))
}
